import type { Metadata } from "next";
import {
  Geist_Mono,
  Libertinus_Serif_Display,
  Reddit_Sans,
} from "next/font/google";
import "./globals.css";

const fontSansCustom = Reddit_Sans({
  variable: "--font-sans-custom",
  subsets: ["latin"],
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontSerifCustom = Libertinus_Serif_Display({
  variable: "--font-serif-custom",
  subsets: ["latin"],
  weight: ["400"],
  display: 'swap',
  fallback: [],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSansCustom.variable} ${fontSerifCustom.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
    >
      <body>{children}</body>
    </html>
  );
}
